CREATE TABLE menu
(
    ID BIGINT(20) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PARENT_ID BIGINT(20),
    CONSTRAINT FK_MENU_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES menu (ID)
);
CREATE INDEX FK_MENU_PARENT_ID ON menu (PARENT_ID);

CREATE TABLE articles
(
    ID BIGINT(20) PRIMARY KEY NOT NULL,
    ADDED_DATE DATE,
    CONTENT LONGTEXT,
    INTRO TEXT,
    TITLE VARCHAR(255),
    MENU_ID BIGINT(20) NOT NULL,
    CONSTRAINT FK_ARTICLES_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES menu (ID)
);
CREATE INDEX FK_ARTICLES_MENU_ID ON articles (MENU_ID);

CREATE TABLE tags
(
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE art_tag
(
    ART_ID BIGINT(20) NOT NULL,
    TAG_ID BIGINT(20) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (ART_ID, TAG_ID),
    CONSTRAINT FK_ART_TAG_ART_ID FOREIGN KEY (ART_ID) REFERENCES articles (ID),
    CONSTRAINT FK_ART_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES tags (ID)
);
CREATE INDEX FK_ART_TAG_TAG_ID ON art_tag (TAG_ID);

CREATE TABLE comments
(
    ID BIGINT(20) PRIMARY KEY NOT NULL,
    ADDED_DATE DATE,
    AUTHOR VARCHAR(255),
    CONTENT LONGTEXT,
    ART_ID BIGINT(20),
    CONSTRAINT FK_COMMENTS_ART_ID FOREIGN KEY (ART_ID) REFERENCES articles (ID)
);
CREATE INDEX FK_COMMENTS_ART_ID ON comments (ART_ID);

CREATE TABLE configuration
(
    keyy VARCHAR(255) PRIMARY KEY NOT NULL,
    value VARCHAR(255)
);

CREATE TABLE sequence
(
    SEQ_NAME VARCHAR(50) PRIMARY KEY NOT NULL,
    SEQ_COUNT DECIMAL(38)
);

CREATE TABLE stags
(
    ID BIGINT(20) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE storages
(
    ID BIGINT(20) PRIMARY KEY NOT NULL,
    CONTENT LONGTEXT,
    INTRO TEXT,
    TITLE VARCHAR(255)
);

CREATE TABLE stags_storages
(
    stags_ID BIGINT(20) NOT NULL,
    storages_ID BIGINT(20) NOT NULL,
    CONSTRAINT FK_STAGS_STORAGES_stags_ID FOREIGN KEY (stags_ID) REFERENCES stags (ID),
    CONSTRAINT FK_STAGS_STORAGES_storages_ID FOREIGN KEY (storages_ID) REFERENCES storages (ID)
);
CREATE INDEX FK_STAGS_STORAGES_storages_ID ON stags_storages (storages_ID);
ALTER TABLE stags_storages ADD CONSTRAINT pk_id PRIMARY KEY (stags_ID, storages_ID);